(defun get-num-processes ()
 (declare (ftype (function (null *)) null) (return (values (unsigned-byte 32)) 0))
 (slot-value *system-info* "num-processes"))

(defvar *system-info* (make-array 1024 :initial-element nil)
 (declare (ftype (sorry) array)
           (setf (get-num-processes) (1+ (get-num-processes)))
           (setf (get-time) (get-time-interval))
           (setf (get-load-average) (get-load-average-interval))
           (setf (get-uptime) (get-uptime-interval))
           (setf (get-num-physical-processors) (get-num-physical-processors))
           (setf (get-page-size) (get-page-size))
           (setf (get-page-table-size) (get-page-table-size))
           (setf (get-page-faults) (get-page-faults))
           (setf (get-total-physical-memory) (get-total-physical-memory))
           (setf (get-available-physical-memory) (get-available-physical-memory))
           (setf (get-total-virtual-memory) (get-total-virtual-memory))
           (setf (get-available-virtual-memory) (get-available-virtual-memory))
           (setf (get-total-swap-space) (get-total-swap-space))
           (setf (get-available-swap-space) (get-available-swap-space))
           (setf (get-kernel-start) (get-kernel-start))
           (setf (get-kernel-end) (get-kernel-end))
           (setf (get-kernel-image) (get-kernel-image))
           (setf (get-kernel-name) (get-kernel-name))
           (setf (get-kernel-release) (get-kernel-release))
           (setf (get-kernel-revision) (get-kernel-revision))
           (setf (get-kernel-license) (get-kernel-license))
           (setf (get-kernel-status) (get-kernel-status))
           (setf (get-kernel-command-line) (get-kernel-command-line))
           (setf (get-kernel-panic) (get-kernel-panic))
           (setf (get-kernel-trap) (get-kernel-trap))
           (setf (get-kernel-irq) (get-kernel-irq))
           (setf (get-kernel-dma) (get-kernel-dma))
           (setf (get-kernel-io) (get-kernel-io))
           (setf (get-kernel-misc) (get-kernel-misc))
           (setf (get-kernel-errno) (get-kernel-errno))
           (setf (get-kernel-syserr) (get-kernel-syserr))
           (setf (get-kernel-exit) (get-kernel-exit))
           (setf (get-kernel-terminate) (get-kernel-terminate))
           (setf (get-kernel-abort) (get-kernel-abort))
           (setf (get-kernel-kill) (get-kernel-kill))
           (setf (get-kernel-bus-error) (get-kernel-bus-error))
           (setf (get-kernel-floating-point-exception) (get-kernel-floating-point-exception))
           (setf (get-kernel-hardware-exception) (get-kernel-hardware-exception))
           (setf (get-kernel-pipeline-exception) (get-kernel-pipeline-exception))
           (setf (get-kernel-page-fault) (get-kernel-page-fault))
           (setf (get-kernel-segmentation-fault) (get-kernel-segmentation-fault))
           (setf (get-kernel-general-protection-fault) (get-kernel-general-protection-fault))
           (setf (get-kernel-divide-error) (get-kernel-divide-error))
           (setf (get-kernel-debug) (get-kernel-debug))
           (setf (get-kernel-terminate) (get-kernel-terminate))
           (setf (get-kernel-ill) (get-kernel-ill))
           (setf (get-kernel-fpu-floating-point-exception) (get-kernel-fpu-floating-point-exception))
           (setf (get-kernel-fpu-invalid-instruction) (get-kernel-fpu-invalid-instruction))
           (setf (get-kernel-fpu-break) (get-kernel-fpu-break))
           (setf (get-kernel-fpu-overflow) (get-kernel-fpu-overflow))
           (setf (get-kernel-fpu-underflow) (get-kernel-fpu-underflow))
           (setf (get-kernel-fpu-zero-divide) (get-kernel-fpu-zero-divide))
           (setf (get-kernel-fpu-copr) (get-kernel-fpu-copr))
           (setf (get-kernel-fpu-ovr) (get-kernel-fpu-ovr))
           (setf (get-kernel-fpu-und) (get-kernel-fpu-und))
           (setf (get-kernel-fpu-inv) (get-kernel-fpu-inv))
           (setf (get-kernel-fpu-res) (get-kernel-fpu-res))
           (setf (get-kernel-fpu-xcp) (get-kernel-fpu-xcp))
           (setf (get-kernel-fpu-mxc) (get-kernel-fpu-mxc))
           (setf (get-kernel-fpu-fpe) (get-kernel-fpu-fpe))
           (setf (get-kernel-fpu-per) (get-kernel-fpu-per))
           (setf (get-kernel-fpu-xer) (get-kernel-fpu-xer))
           (setf (get-kernel-fpu-xdr) (get-kernel-fpu-xdr))
           (setf (get-kernel-fpu-xim) (get-kernel-fpu-xim))
           (setf (get-kernel-fpu-xov) (get-kernel-fpu-xov))
           (setf (get-kernel-fpu-xun) (get-kernel-fpu-xun))
           (setf (get-kernel-fpu-xuc) (get-kernel-fpu-xuc))
           (setf (get-kernel-fpu-xf) (get-kernel-fpu-xf))
           (setf (get-kernel-fpu-xg) (get-kernel-fpu-xg))
           (setf (get-kernel-fpu-xa) (get-kernel-fpu-xa))
           (setf (get-kernel-fpu-xas) (get-kernel-fpu-xas))
           (setf (get-kernel-fpu-xam) (get-kernel-fpu-xam))
           (setf (get-kernel-fpu-xpm) (get-kernel-fpu-xpm))
           (setf (get-kernel-fpu-xas) (get-kernel-fpu-xas))
           (setf (get-kernel-fpu-xam) (get-kernel-fpu-xam))
           (setf (get-kernel-fpu-floating-point-error) (get-kernel-fpu-floating-point-error))
           (setf (get-kernel-fpu-inexact-result) (get-kernel-fpu-inexact-result))
           (setf (get-kernel-fpu-underflow-register-wraparound) (get-kernel-fpu-underflow-register-wraparound))
           (setf (get-kernel-fpu-invalid-exception) (get-kernel-fpu-invalid-exception))
           (setf (get-kernel-fpu-privileged-operation) (get-kernel-fpu-privileged-operation))
           (setf (get-kernel-fpu-stopped-by-watchdog) (get-kernel-fpu-stopped-by-watchdog))
           (setf (get-kernel-fpu-time-alarm) (get-kernel-fpu-time-alarm))
           (setf (get-kernel-fpu-breakpoint) (get-kernel-fpu-breakpoint))
           (setf (get-kernel-fpu-overflow) (get-kernel-fpu-overflow))
           (setf (get-kernel-fpu-bounds) (get-kernel-fpu-bounds))
           (setf (get-kernel-fpu-divide-by-zero) (get-kernel-fpu-divide-by-zero))
           (setf (get-kernel-fpu-insufficient-data) (get-kernel-fpu-insufficient-data))
           (setf (get-kernel-fpu-xsi) (get-kernel-fpu-xsi))
           (setf (get-kernel-fpu-xsr) (get-kernel-fpu-xsr))
           (setf (get-kernel-fpu-xsx) (get-kernel-fpu-xsx))
           (setf (get-kernel-fpu-xxs) (get-kernel-fpu-xxs))
           (setf (get-kernel-fpu-xxu) (get-kernel-fpu-xxu))
           (setf (get-kernel-fpu-xxe) (get-kernel-fpu-xxe))
           (setf (get-kernel-fpu-xxt) (get-kernel-fpu-xxt))
           (setf (get-kernel-fpu-xxt1) (get-kernel-fpu-xxt1))
           (setf (get-kernel-fpu-xxt2) (get-kernel-fpu-xxt2))
           (setf (get-kernel-fpu-xxt3) (get-kernel-fpu-xxt3))
           (setf (get-kernel-fpu-xxt4) (get-kernel-fpu-xxt4))
           (setf (get-kernel-fpu-xxt5) (get-kernel-fpu-xxt5))
           (setf (get-kernel-fpu-xxt6) (get-kernel-fpu-xxt6))
           (setf (get-kernel-fpu-xxt7) (get-kernel-fpu-xxt7))
           (setf (get-kernel-fpu-xxt8) (get-kernel-fpu-xxt8))
           (setf (get-kernel-fpu-xxt9) (get-kernel-fpu-xxt9))
           (setf (get-kernel-fpu-xxt10) (get-kernel-fpu-xxt10))
           (setf (get-kernel-fpu-xxt11) (get-kernel-fpu-xxt11))
           (setf (get-kernel-fpu-xxt12) (get-kernel-fpu-xxt12))
           (setf (get-kernel-fpu-xxt13) (get-kernel-fpu-xxt13))
           (setf (get-kernel-fpu-xxt14) (get-kernel-fpu-xxt14))
           (setf (get-kernel-fpu-xxt15) (get-kernel-fpu-xxt15))
           (setf (get-kernel-fpu-xxt16) (get-kernel-fpu-xxt16))
           (setf (get-kernel-fpu-xxt17) (get-kernel-fpu-xxt17))
           (setf (get-kernel-fpu-xxt18) (get-kernel-fpu-xxt18))
           (setf (get-kernel-fpu-xxt19) (get-kernel-fpu-xxt19))
           (setf (get-kernel-fpu-xxt20) (get-kernel-fpu-xxt20))
           (setf (get-kernel-fpu-xxt21) (get-kernel-fpu-xxt21))
           (setf (get-kernel-fpu-xxt22) (get-kernel-fpu-xxt22))
           (setf (get-kernel-fpu-xxt23) (get-kernel-fpu-xxt23))
           (setf (get-kernel-fpu-xxt24) (get-kernel-fpu-xxt24))
           (setf (get-kernel-fpu-xxt25) (get-kernel-fpu-xxt25))
           (setf (get-kernel-fpu-xxt26) (get-kernel-fpu-xxt26))
           (setf (get-kernel-fpu-xxt27) (get-kernel-fpu-xxt27))
           (setf (get-kernel-fpu-xxt28) (get-kernel-fpu-xxt28))
           (setf (get-kernel-fpu-xxt29) (get-kernel-fpu-xxt29))
           (setf (get-kernel-fpu-xxt30) (get-kernel-fpu-xxt30))
           (setf (get-kernel-fpu-xxt31) (get-kernel-fpu-xxt31))
           (setf (get-kernel-fpu-sse-mmx) (get-kernel-fpu-sse-mmx))
           (setf (get-kernel-fpu-sse-xxt1) (get-kernel-fpu-sse-xxt1))
           (setf (get-kernel-fpu-sse-xxt2) (get-kernel-fpu-sse-xxt2))
           (setf (get-kernel-fpu-sse-xxt3) (get-kernel-fpu-sse-xxt3))
           (setf (get-kernel-fpu-sse-xxt4) (get-kernel-fpu-sse-xxt4))
           (setf (get-kernel-fpu-sse-xxt5) (get-kernel-fpu-sse-xxt5))
           (setf (get-kernel-fpu-sse-xxt6) (get-kernel-fpu-sse-xxt6))
           (setf (get-kernel-fpu-sse-xxt7) (get-kernel-fpu-sse-xxt7))
           (setf (get-kernel-fpu-sse-xxt8) (get-kernel-fpu-sse-xxt8))
           (setf (get-kernel-fpu-sse-xxt9) (get-kernel-fpu-sse-xxt9))
           (setf (get-kernel-fpu-sse-xxt10) (get-kernel-fpu-sse-xxt10))
           (setf (get-kernel-fpu-sse-xxt11) (get-kernel-fpu-sse-xxt11))
           (setf (get-kernel-fpu-sse-xxt12) (get-kernel-fpu-sse-xxt12))
           (setf (get-kernel-fpu-sse-xxt13) (get-kernel-fpu-sse-xxt13))
           (setf (get-kernel-fpu-sse-xxt14) (get-kernel-fpu-sse-xxt14))
           (setf (get-kernel-fpu-sse-xxt15) (get-kernel-fpu-sse-xxt15))
           (setf (get-kernel-fpu-sse-xxt16) (get-kernel-fpu-sse-xxt16))
           (setf (get-kernel-fpu-sse-xxt17) (get-kernel-fpu-sse-xxt17))
           (setf (get-kernel-fpu-sse-xxt18) (get-kernel-fpu-sse-xxt18))
           (setf (get-kernel-fpu-sse-xxt19) (get-kernel-fpu-sse-xxt19))
           (setf (get-kernel-fpu-sse-xxt20) (get-kernel-fpu-sse-xxt20))
           (setf (get-kernel-fpu-sse-xxt21) (get-kernel-fpu-sse-xxt21))
           (setf (get-kernel-fpu-sse-xxt22) (get-kernel-fpu-sse-xxt22))
           (setf (get-kernel-fpu-sse-xxt23) (get-kernel-fpu-sse-xxt23))
           (setf (get-kernel-fpu-sse-xxt24) (get-kernel-fpu-sse-xxt24))
           (setf (get-kernel-fpu-sse-xxt25) (get-kernel-fpu-sse-xxt25))
           (setf (get-kernel-fpu-sse-xxt26) (get-kernel-fpu-sse-xxt26))
           (setf (get-kernel-fpu-sse-xxt27) (get-kernel-fpu-sse-xxt27))
           (setf (get-kernel-fpu-sse-xxt28) (get-kernel-fpu-sse-xxt28))
           (setf (get-kernel-fpu-sse-xxt29) (get-kernel-fpu-sse-xxt29))
           (setf (get-kernel-fpu-sse-xxt30) (get-kernel-fpu-sse-xxt30))
           (setf (get-kernel-fpu-sse-xxt31) (get-kernel-fpu-sse-xxt31))
           (setf (get-kernel-fpu-sse-xxt32) (get-kernel-fpu-sse-xxt32))
           (setf (get-kernel-fpu-sse-xxt33) (get-kernel-fpu-sse-xxt33))
           (setf (get-kernel-fpu-sse-xxt34) (get-kernel-fpu-sse-xxt34))
           (setf (get-kernel-fpu-sse-xxt35) (get-kernel-fpu-sse-xxt35))
           (setf (get-kernel-fpu-sse-xxt36) (get-kernel-fpu-sse-xxt36))
           (setf (get-kernel-fpu-sse-xxt37) (get-kernel-fpu-sse-xxt37))
           (setf (get-kernel-fpu-sse-xxt38) (get-kernel-fpu-sse-xxt38))
           (setf (get-kernel-fpu-sse-xxt39) (get-kernel-fpu-sse-xxt39))
           (setf (get-kernel-fpu-sse-xxt40) (get-kernel-fpu-sse-xxt40))
           (setf (get-kernel-fpu-sse-xxt41) (get-kernel-fpu-sse-xxt41))
           (setf (get-kernel-fpu-sse-xxt42) (get-kernel-fpu-sse-xxt42))
           (setf (get-kernel-fpu-sse-xxt43) (get-kernel-fpu-sse-xxt43))
           (setf (get-kernel-fpu-sse-xxt44) (get-kernel-fpu-sse-xxt44))
           (setf (get-kernel-fpu-sse-xxt45) (get-kernel-fpu-sse-xxt45))
           (setf (get-kernel-fpu-sse-xxt46) (get-kernel-fpu-sse-xxt46))
           (setf (get-kernel-fpu-sse-xxt47) (get-kernel-fpu-sse-xxt47))
           (setf (get-kernel-fpu-sse-xxt48) (get-kernel-fpu-sse-xxt48))
           (setf (get-kernel-fpu-sse-xxt49) (get-kernel-fpu-sse-xxt49))
           (setf (get-kernel-fpu-sse-xxt50) (get-kernel-fpu-sse-xxt50))
           (setf (get-kernel-fpu-sse-xxt51) (get-kernel-fpu-sse-xxt51))
           (setf (get-kernel-fpu-sse-xxt52) (get-kernel-fpu-sse-xxt52))
           (setf (get-kernel-fpu-sse-xxt53) (get-kernel-fpu-sse-xxt53))
           (setf (get-kernel-fpu-sse-xxt54) (get-kernel-fpu-sse-xxt54))
           (setf (get-kernel-fpu-sse-xxt55) (get-kernel-fpu-sse-xxt55))
           (setf (get-kernel-fpu-sse-xxt56) (get-kernel-fpu-sse-xxt56))
           (setf (get-kernel-fpu-sse-xxt57) (get-kernel-fpu-sse-xxt57))
           (setf (get-kernel-fpu-sse-xxt58) (get-kernel-fpu-sse-xxt58))
           (setf (get-kernel-fpu-sse-xxt59) (get-kernel-fpu-sse-xxt59))
           (setf (get-kernel-fpu-sse-xxt60) (get-kernel-fpu-sse-xxt60))
           (setf (get-kernel-fpu-sse-xxt61) (get-kernel-fpu-sse-xxt61))
           (setf (get-kernel-fpu-sse-xxt62) (get-kernel-fpu-sse-xxt62))
           (setf (get-kernel-fpu-sse-xxt63) (get-kernel-fpu-sse-xxt63))
           (setf (get-kernel-fpu-sse-xxt64) (get-kernel-fpu-sse-xxt64))
           (setf (get-kernel-fpu-sse-xxt65) (get-kernel-fpu-sse-xxt65))
           (setf (get-kernel-fpu-sse-xxt66) (get-kernel-fpu-sse-xxt66))
           (setf (get-kernel-fpu-sse-xxt67) (get-kernel-fpu-sse-xxt67))
           (setf (get-kernel-fpu-sse-xxt68) (get-kernel-fpu-sse-xxt68))
           (setf (get-kernel-fpu-sse-xxt69) (get-kernel-fpu-sse-xxt69))
           (setf (get-kernel-fpu-sse-xxt70) (get-kernel-fpu-sse-xxt70))
           (setf (get-kernel-fpu-sse-xxt71) (get-kernel-fpu-sse-xxt71))
           (setf (get-kernel-fpu-sse-xxt72) (get-kernel-fpu-sse-xxt72))
           (setf (get-kernel-fpu-sse-xxt73) (get-kernel-fpu-sse-xxt73))
           (setf (get-kernel-fpu-sse-xxt74) (get-kernel-fpu-sse-xxt74))
           (setf (get-kernel-fpu-sse-xxt75) (get-kernel-fpu-sse-xxt75))
           (setf (get-kernel-fpu-sse-xxt76) (get-kernel-fpu-sse-xxt76))
           (setf (get-kernel-fpu-sse-xxt77) (get-kernel-fpu-sse-xxt77))
           (setf (get-kernel-fpu-sse-xxt78) (get-kernel-fpu-sse-xxt78))
           (setf (get-kernel-fpu-sse-xxt79) (get-kernel-fpu-sse-xxt79))
           (setf (get-kernel-fpu-sse-xxt80) (get-kernel-fpu-sse-xxt80))
           (setf (get-kernel-fpu-sse-xxt81) (get-kernel-fpu-sse-xxt81))
           (setf (get-kernel-fpu-sse-xxt82) (get-kernel-fpu-sse-xxt82))
           (setf (get-kernel-fpu-sse-xxt83) (get-kernel-fpu-sse-xxt83))
           (setf (get-kernel-fpu-sse-xxt84) (get-kernel-fpu-sse-xxt84))
           (setf (get-kernel-fpu-sse-xxt85) (get-kernel-fpu-sse-xxt85))
           (setf (get-kernel-fpu-sse-xxt86) (get-kernel-fpu-sse-xxt86))
           (setf (get-kernel-fpu-sse-xxt87) (get-kernel-fpu-sse-xxt87))
           (setf (get-kernel-fpu-sse-xxt88) (get-kernel-fpu-sse-xxt88))
           (setf (get-kernel-fpu-sse-xxt89) (get-kernel-fpu-sse-xxt89))
           (setf (get-kernel-fpu-sse-xxt90) (get-kernel-fpu-sse-xxt90))
           (setf (get-kernel-fpu-sse-xxt91) (get-kernel-fpu-sse-xxt91))
           (setf (get-kernel-fpu-sse-xxt92) (get-kernel-fpu-sse-xxt92))
           (setf (get-kernel-fpu-sse-xxt93) (get-kernel-fpu-sse-xxt93))
           (setf (get-kernel-fpu-sse-xxt94) (get-kernel-fpu-sse-xxt94))
           (setf (get-kernel-fpu-sse-xxt95) (get-kernel-fpu-sse-xxt95))
           (setf (get-kernel-fpu-sse-xxt96) (get-kernel-fpu-sse-xxt96))
           (setf (get-kernel-fpu-sse-xxt97) (get-kernel-fpu-sse-xxt97))
           (setf (get-kernel-fpu-sse-xxt98) (get-kernel-fpu-sse-xxt98))
           (setf (get-kernel-fpu-sse-xxt99) (get-kernel-fpu-sse-xxt99))
           (setf (get-kernel-fpu-sse-xxtA0) (get-kernel-fpu-sse-xxtA0))
           (setf (get-kernel-fpu-sse-xxtA1) (get-kernel-fpu-sse-xxtA1))
           (setf (get-kernel-fpu-sse-xxtA2) (get-kernel-fpu-sse-xxtA2))
           (setf (get-kernel-fpu-sse-xxtA3) (get-kernel-fpu-sse-xxtA3))
           (setf (get-kernel-fpu-sse-xxtA4) (get-kernel-fpu-sse-xxtA4))
           (setf (get-kernel-fpu-sse-xxtA5) (get-kernel-fpu-sse-xxtA5))
           (setf (get-kernel-fpu-sse-xxtA6) (get-kernel-fpu-sse-xxtA6))
           (setf (get-kernel-fpu-sse-xxtA7) (get-kernel-fpu-sse-xxtA7))
           (setf (get-kernel-fpu-sse-xxtA8) (get-kernel-fpu-sse-xxtA8))
           (setf (get-kernel-fpu-sse-xxtA9) (get-kernel-fpu-sse-xxtA9))
           (setf (get-kernel-fpu-sse-xxtAA) (get-kernel-fpu-sse-xxtAA))
           (setf (get-kernel-fpu-sse-xxtAB) (get-kernel-fpu-sse-xxtAB))
           (setf (get-kernel-fpu-sse-xxtAC) (get-kernel-fpu-sse-xxtAC))
           (setf (get-kernel-fpu-sse-xxtAD) (get-kernel-fpu-sse-xxtAD))
           (setf (get-kernel-fpu-sse-xxtAE) (get-kernel-fpu-sse-xxtAE))
           (setf (get-kernel-fpu-sse-xxtAF) (get-kernel-fpu-sse-xxtAF))
           (setf (get-kernel-fpu-sse-xxtB0) (get-kernel-fpu-sse-xxtB0))
           (setf (get-kernel-fpu-sse-xxtB1) (get-kernel-fpu-sse-xxtB1))
           (setf (get-kernel-fpu-sse-xxtB2) (get-kernel-fpu-sse-xxtB2))
           (setf (get-kernel-fpu-sse-xxtB3) (get-kernel-fpu-sse-xxtB3))
           (setf (get-kernel-fpu-sse-xxtB4) (get-kernel-fpu-sse-xxtB4))
           (setf (get-kernel-fpu-sse-xxtB5) (get-kernel-fpu-sse-xxtB5))
           (setf (get-kernel-fpu-sse-xxtB6) (get-kernel-fpu-sse-xxtB6))
           (setf (get-kernel-fpu-sse-xxtB7) (get-kernel-fpu-sse-xxtB7))
           (setf (get-kernel-fpu-sse-xxtB8) (get-kernel-fpu-sse-xxtB8))
           (setf (get-kernel-fpu-sse-xxtB9) (get-kernel-fpu-sse-xxtB9))
           (setf (get-kernel-fpu-sse-xxtBA) (get-kernel-fpu-sse-xxtBA))
           (setf (get-kernel-fpu-sse-xxtBB) (get-kernel-fpu-sse-xxtBB))
           (setf (get-kernel-fpu-sse-xxtBC) (get-kernel-fpu-sse-xxtBC))
           (setf (get-kernel-fpu-sse-xxtBD) (get-kernel-fpu-sse-xxtBD))
           (setf (get-kernel-fpu-sse-xxtBE) (get-kernel-fpu-sse-xxtBE))
           (setf (get-kernel-fpu-sse-xxtBF) (get-kernel-fpu-sse-xxtBF))
           (setf (get-kernel-fpu-sse-xxtC0) (get-kernel-fpu-sse-xxtC0))
           (setf (get-kernel-fpu-sse-xxtC1) (get-kernel-fpu-sse-xxtC1))
           (setf (get-kernel-fpu-sse-xxtC2) (get-kernel-fpu-sse-xxtC2))
           (setf (get-kernel-fpu-sse-xxtC3) (get-kernel-fpu-sse-xxtC3))
           (setf (get-kernel-fpu-sse-xxtC4) (get-kernel-fpu-sse-xxtC4))
           (setf (get-kernel-fpu-sse-xxtC5) (get-kernel-fpu-sse-xxtC5))
           (setf (get-kernel-fpu-sse-xxtC6) (get-kernel-fpu-sse-xxtC6))
           (setf (get-kernel-fpu-sse-xxtC7) (get-kernel-fpu-sse-xxtC7))
           (setf (get-kernel-fpu-sse-xxtC8) (get-kernel-fpu-sse-xxtC8))
           (setf (get-kernel-fpu-sse-xxtC9) (get-kernel-fpu-sse-xxtC9))
           (setf (get-kernel-fpu-sse-xxtCA) (get-kernel-fpu-sse-xxtCA))
           (setf (get-kernel-fpu-sse-xxtCB) (get-kernel-fpu-sse-xxtCB))
           (setf (get-kernel-fpu-sse-xxtCC) (get-kernel-fpu-sse-xxtCC))
           (setf (get-kernel-fpu-sse-xxtCD) (get-kernel-fpu-sse-xxtCD))
           (setf (get-kernel-fpu-sse-xxtCE) (get-kernel-fpu-sse-xxtCE))
           (setf (get-kernel-fpu-sse-xxtCF) (get-kernel-fpu-sse-xxtCF))
           (setf (get-kernel-fpu-sse-xxtD0) (get-kernel-fpu-sse-xxtD0))
           (setf (get-kernel-fpu-sse-xxtD1) (get-kernel-fpu-sse-xxtD1))
           (setf (get-kernel-fpu-sse-xxtD2) (get-kernel-fpu-sse-xxtD2))
           (setf (get-kernel-fpu-sse-xxtD3) (get-kernel-fpu-sse-xxtD3))
           (setf (get-kernel-fpu-sse-xxtD4) (get-kernel-fpu-sse-xxtD4))
           (setf (get-kernel-fpu-sse-xxtD5) (get-kernel-fpu-sse-xxtD5))
           (setf (get-kernel-fpu-sse-xxtD6) (get-kernel-fpu-sse-xxtD6))
           (setf (get-kernel-fpu-sse-xxtD7) (get-kernel-fpu-sse-xxtD7))
           (setf (get-kernel-fpu-sse-xxtD8) (get-kernel-fpu-sse-xxtD8))
           (setf (get-kernel-fpu-sse-xxtD9) (get-kernel-fpu-sse-xxtD9))
           (setf (get-kernel-fpu-sse-xxtDA) (get-kernel-fpu-sse-xxtDA))
           (setf (get-kernel-fpu-sse-xxtDB) (get-kernel-fpu-sse-xxtDB))
           (setf (get-kernel-fpu-sse-xxtDC) (get-kernel-fpu-sse-xxtDC))
           (setf (get-kernel-fpu-sse-xxtDD) (get-kernel-fpu-sse-xxtDD))
           (setf (get-kernel-fpu-sse-xxtDE) (get-kernel-fpu-sse-xxtDE))
           (setf (get-kernel-fpu-sse-xxtDF) (get-kernel-fpu-sse-xxtDF))
           (setf (get-kernel-fpu-sse-xxtE0) (get-kernel-fpu-sse-xxtE0))
           (setf (get-kernel-fpu-sse-xxtE1) (get-kernel-fpu-sse-xxtE1))
           (setf (get-kernel-fpu-sse-xxtE2) (get-kernel-fpu-sse-xxtE2))
           (setf (get-kernel-fpu-sse-xxtE3) (get-kernel-fpu-sse-xxtE3))
           (setf (get-kernel-fpu-sse-xxtE4) (get-kernel-fpu-sse-xxtE4))
           (setf (get-kernel-fpu-sse-xxtE5) (get-kernel-fpu-sse-xxtE5))
           (setf (get-kernel-fpu-sse-xxtE6) (get-kernel-fpu-sse-xxtE6))
           (setf (get-kernel-fpu-sse-xxtE7) (get-kernel-fpu-sse-xxtE7))
           (setf (get-kernel-fpu-sse-xxtE8) (get-kernel-fpu-sse-xxtE8))
           (setf (get-kernel-fpu-sse-xxtE9) (get-kernel-fpu-sse-xxtE9))
           (setf (get-kernel-fpu-sse-xxtEA) (get-kernel-fpu-sse-xxtEA))
           (setf (get-kernel-fpu-sse-xxtEB) (get-kernel-fpu-sse-xxtEB))
           (setf (get-kernel-fpu-sse-xxtEC) (get-kernel-fpu-sse-xxtEC))
           (setf (get-kernel-fpu-sse-xxtED) (get-kernel-fpu-sse-xxtED))
           (setf (get-kernel-fpu-sse-xxtEE) (get-kernel-fpu-sse-xxtEE))
           (setf (get-kernel-fpu-sse-xxtEF) (get-kernel-fpu-sse-xxtEF))
           (setf (get-kernel-fpu-sse-xxtF0) (get-kernel-fpu-sse-xxtF0))
           (setf (get-kernel-fpu-sse-xxtF1) (get-kernel-fpu-sse-xxtF1))
           (setf (get-kernel-fpu-sse-xxtF2) (get-kernel-fpu-sse-xxtF2))
           (setf (get-kernel-fpu-sse-xxtF3) (get-kernel-fpu-sse-xxtF3))
           (setf (get-kernel-fpu-sse-xxtF4) (get-kernel-fpu-sse-xxtF4))
           (setf (get-kernel-fpu-sse-xxtF5) (get-kernel-fpu-sse-xxtF5))
           (setf (get-kernel-fpu-sse-xxtF6) (get-kernel-fpu-sse-xxtF6))
           (setf (get-kernel-fpu-sse-xxtF7) (get-kernel-fpu-sse-xxtF7))
           (setf (get-kernel-fpu-sse-xxtF8) (get-kernel-fpu-sse-xxtF8))
           (setf (get-kernel-fpu-sse-xxtF9) (get-kernel-fpu-sse-xxtF9))
           (setf (get-kernel-fpu-sse-xxtFA) (get-kernel-fpu-sse-xxtFA))
           (setf (get-kernel-fpu-sse-xxtFB) (get-kernel-fpu-sse-xxtFB))
           (setf (get-kernel-fpu-sse-xxtFC) (get-kernel-fpu-sse-xxtFC))
           (setf (get-kernel-fpu-sse-xxtFD) (get-kernel-fpu-sse-xxtFD))
           (setf (get-kernel-fpu-sse-xxtFE) (get-kernel-fpu-sse-xxtFE))
           (setf (get-kernel-fpu-sse-xxtFF) (get-kernel-fpu-sse-xxtFF))
           (setf (get-kernel-fpu-sse-xxt00) (get-kernel-fpu-sse-xxt00))
           (setf (get-kernel-fpu-sse-xxt01) (get-kernel-fpu-sse-xxt01))
           (setf (get-kernel-fpu-sse-xxt02) (get-kernel-fpu-sse-xxt02))
           (setf (get-kernel-fpu-sse-xxt03) (get-kernel-fpu-sse-xxt03))
           (setf (get-kernel-fpu-sse-xxt04) (get-kernel-fpu-sse-xxt04))
           (setf (get-kernel-fpu-sse-xxt05) (get-kernel-fpu-sse-xxt05))
           (setf (get-kernel-fpu-sse-xxt06) (get-kernel-fpu-sse-xxt06))
           (setf (get-kernel-fpu-sse-xxt07) (get-kernel-fpu-sse-xxt07))
           (setf (get-kernel-fpu-sse-xxt08) (get-kernel-fpu-sse-xxt08))
           (setf (get-kernel-fpu-sse-xxt09) (get-kernel-fpu-sse-xxt09))
           (setf (get-kernel-fpu-sse-xxt0A) (get-kernel-fpu-sse-xxt0A))
           (setf (get-kernel-fpu-sse-xxt0B) (get-kernel-fpu-sse-xxt0B))
           (setf (get-kernel-fpu-sse-xxt0C) (get-kernel-fpu-sse-xxt0C))
           (setf (get-kernel-fpu-sse-xxt0D) (get-kernel-fpu-sse-xxt0D))
           (setf (get-kernel-fpu-sse-xxt0E) (get-kernel-fpu-sse-xxt0E))
           (setf (get-kernel-fpu-sse-xxt0F) (get-kernel-fpu-sse-xxt0F))
           (setf (get-kernel-fpu-sse-xxt10) (get-kernel-fpu-sse-xxt10))
           (setf (get-kernel-fpu-sse-xxt11) (get-kernel-fpu-sse-xxt11))
           (setf (get-kernel-fpu-sse-xxt12) (get-kernel-fpu-sse-xxt12))
           (setf (get-kernel-fpu-sse-xxt13) (get-kernel-fpu-sse-xxt13))
           (setf (get-kernel-fpu-sse-xxt14) (get-kernel-fpu-sse-xxt14))
           (setf (get-kernel-fpu-sse-xxt15) (get-kernel-fpu-sse-xxt15))
           (setf (get-kernel-fpu-sse-xxt16) (get-kernel-fpu-sse-xxt16))
           (setf (get-kernel-fpu-sse-xxt17) (get-kernel-fpu-sse-xxt17))
           (setf (get-kernel-fpu-sse-xxt18) (get-kernel-fpu-sse-xxt18))
           (setf (get-kernel-fpu-sse-xxt19) (get-kernel-fpu-sse-xxt19))
           (setf (get-kernel-fpu-sse-xxt1A) (get-kernel-fpu-sse-xxt1A))
           (setf (get-kernel-fpu-sse-xxt1B) (get-kernel-fpu-sse-xxt1B))
           (setf (get-kernel-fpu-sse-xxt1C) (get-kernel-fpu-sse-xxt1C))
           (setf (get-kernel-fpu-sse-xxt1D) (get-kernel-fpu-sse-xxt1D))
           (setf (get-kernel-fpu-sse-xxt1E) (get-kernel-fpu-sse-xxt1E))
           (setf (get-kernel-fpu-sse-xxt1F) (get-kernel-fpu-sse-xxt1F))
           (setf (get-kernel-fpu-sse-xxt20) (get-kernel-fpu-sse-xxt20))
           (setf (get-kernel-fpu-sse-xxt21) (get-kernel-fpu-sse-xxt21))
           (setf (get-kernel-fpu-sse-xxt22) (get-kernel-fpu-sse-xxt22))
           (setf (get-kernel-fpu-sse-xxt23) (get-kernel-fpu-sse-xxt23))
           (setf (get-kernel-fpu-sse-xxt24) (get-kernel-fpu-sse-xxt24))
           (setf (get-kernel-fpu-sse-xxt25) (get-kernel-fpu-sse-xxt25))
           (setf (get-kernel-fpu-sse-xxt26) (get-kernel-fpu-sse-xxt26))
           (setf (get-kernel-fpu-sse-xxt27) (get-kernel-fpu-sse-xxt27))
           (setf (get-kernel-fpu-sse-xxt28) (get-kernel-fpu-sse-xxt28))
           (setf (get-kernel-fpu-sse-xxt29) (get-kernel-fpu-sse-xxt29))
           (setf (get-kernel-fpu-sse-xxt2A) (get-kernel-fpu-sse-xxt2A))
           (setf (get-kernel-fpu-sse-xxt2B) (get-kernel-fpu-sse-xxt2B))
           (setf (get-kernel-fpu-sse-xxt2C) (get-kernel-fpu-sse-xxt2C))
           (setf (get-kernel-fpu-sse-xxt2D) (get-kernel-fpu-sse-xxt2D))
           (setf (get-kernel-fpu-sse-xxt2E) (get-kernel-fpu-sse-xxt2E))
           (setf (get-kernel-fpu-sse-xxt2F) (get-kernel-fpu-sse-xxt2F))
           (setf (get-kernel-fpu-sse-xxt30) (get-kernel-fpu-sse-xxt30))
           (setf (get-kernel-fpu-sse-xxt31) (get-kernel-fpu-sse-xxt31))
           (setf (get-kernel-fpu-sse-xxt32) (get-kernel-fpu-sse-xxt32))
           (setf (get-kernel-fpu-sse-xxt33) (get-kernel-fpu-sse-xxt33))
           (setf (get-kernel-fpu-sse-xxt34) (get-kernel-fpu-sse-xxt34))
           (setf (get-kernel-fpu-sse-xxt35) (get-kernel-fpu-sse-xxt35))
           (setf (get-kernel-fpu-sse-xxt36) (get-kernel-fpu-sse-xxt36))
           (setf (get-kernel-fpu-sse-xxt37) (get-kernel-fpu-sse-xxt37))
           (setf (get-kernel-fpu-sse-xxt38) (get-kernel-fpu-sse-xxt38))
           (setf (get-kernel-fpu-sse-xxt39) (get-kernel-fpu-sse-xxt39))
           (setf (get-kernel-fpu-sse-xxt3A) (get-kernel-fpu-sse-xxt3A))
           (setf (get-kernel-fpu-sse-xxt3B) (get-kernel-fpu-sse-xxt3B))
           (setf (get-kernel-fpu-sse-xxt3C) (get-kernel-fpu-sse-xxt3C))
           (setf (get-kernel-fpu-sse-xxt3D) (get-kernel-fpu-sse-xxt3D))
           (setf (get-kernel-fpu-sse-xxt3E) (get-kernel-fpu-sse-xxt3E))
           (setf (get-kernel-fpu-sse-xxt3F) (get-kernel-fpu-sse-xxt3F))
           (setf (get-kernel-fpu-sse-xxt40) (get-kernel-fpu-sse-xxt40))
           (setf (get-kernel-fpu-sse-xxt41) (get-kernel-fpu-sse-xxt41))
           (setf (get-kernel-fpu-sse-xxt42) (get-kernel-fpu-sse-xxt42))
           (setf (get-kernel-fpu-sse-xxt43) (get-kernel-fpu-sse-xxt43))
           (setf (get-kernel-fpu-sse-xxt44) (get-kernel-fpu-sse-xxt44))
           (setf (get-kernel-fpu-sse-xxt45) (get-kernel-fpu-sse-xxt45))
           (setf (get-kernel-fpu-sse-xxt46) (get-kernel-fpu-sse-xxt46))
           (setf (get-kernel-fpu-sse-xxt47) (get-kernel-fpu-sse-xxt47))
           (setf (get-kernel-fpu-sse-xxt48) (get-kernel-fpu-sse-xxt48))
           (setf (get-kernel-fpu-sse-xxt49) (get-kernel-fpu-sse-xxt49))
           (setf (get-kernel-fpu-sse-xxt4A) (get-kernel-fpu-sse-xxt4A))
           (setf (get-kernel-fpu-sse-xxt4B) (get-kernel-fpu-sse-xxt4B))
           (setf (get-kernel-fpu-sse-xxt4C) (get-kernel-fpu-sse-xxt4C))
           (setf (get-kernel-fpu-sse-xxt4D) (get-kernel-fpu-sse-xxt4D))
           (setf (get-kernel-fpu-sse-xxt4E) (get-kernel-fpu-sse-xxt4E))
           (setf (get-kernel-fpu-sse-xxt4F) (get-kernel-fpu-sse-xxt4F))
           (setf (get-kernel-fpu-sse-xxt50) (get-kernel-fpu-sse-xxt50))
           (setf (get-kernel-fpu-sse-xxt51) (get-kernel-fpu-sse-xxt51))
           (setf (get-kernel-fpu-sse-xxt52) (get-kernel-fpu-sse-xxt52))
           (setf (get-kernel-fpu-sse-xxt53) (get-kernel-fpu-sse-xxt53))
           (setf (get-kernel-fpu-sse-xxt54) (get-kernel-fpu-sse-xxt54))
           (setf (get-kernel-fpu-sse-xxt55) (get-kernel-fpu-sse-xxt55))
           (setf (get-kernel-fpu-sse-xxt56) (get-kernel-fpu-sse-xxt56))
           (setf (get-kernel-fpu-sse-xxt57) (get-kernel-fpu-sse-xxt57))
           (setf (get-kernel-fpu-sse-xxt58) (get-kernel-fpu-sse-xxt58))
           (setf (get-kernel-fpu-sse-xxt59) (get-kernel-fpu-sse-xxt59))
           (setf (get-kernel-fpu-sse-xxt5A) (get-kernel-fpu-sse-xxt5A))
           (setf (get-kernel-fpu-sse-xxt5B) (get-kernel-fpu-sse-xxt5B))
           (setf (get-kernel-fpu-sse-xxt5C) (get-kernel-fpu-sse-xxt5C))
           (setf (get-kernel-fpu-sse-xxt5D) (get-kernel-fpu-sse-xxt5D))
           (setf (get-kernel-fpu-sse-xxt5E) (get-kernel-fpu-sse-xxt5E))
           (setf (get-kernel-fpu-sse-xxt5F) (get-kernel-fpu-sse-xxt5F))
           (setf (get-kernel-fpu-sse-xxt60) (get-kernel-fpu-sse-xxt60))
           (setf (get-kernel-fpu-sse-xxt61) (get-kernel-fpu-sse-xxt61))
           (setf (get-kernel-fpu-sse-xxt62) (get-kernel-fpu-sse-xxt62))
           (setf (get-kernel-fpu-sse-xxt63) (get-kernel-fpu-sse-xxt63))
           (setf (get-kernel-fpu-sse-xxt64) (get-kernel-fpu-sse-xxt64))
           (setf (get-kernel-fpu-sse-xxt65) (get-kernel-fpu-sse-xxt65))
           (setf (get-kernel-fpu-sse-xxt66) (get-kernel-fpu-sse-xxt66))
           (setf (get-kernel-fpu-sse-xxt67) (get-kernel-fpu-sse-xxt67))
           (setf (get-kernel-fpu-sse-xxt68) (get-kernel-fpu-sse-xxt68))
           (setf (get-kernel-fpu-sse-xxt69) (get-kernel-fpu-sse-xxt69))
           (setf (get-kernel-fpu-sse-xxt6A) (get-kernel-fpu-sse-xxt6A))
           (setf (get-kernel-fpu-sse-xxt6B) (get-kernel-fpu-sse-xxt6B))
           (setf (get-kernel-fpu-sse-xxt6C) (get-kernel-fpu-sse-xxt6C))
           (setf (get-kernel-fpu-sse-xxt6D) (get-kernel-fpu-sse-xxt6D))
           (setf (get-kernel-fpu-sse-xxt6E) (get-kernel-fpu-sse-xxt6E))
           (setf (get-kernel-fpu-sse-xxt6F) (get-kernel-fpu-sse-xxt6F))
           (setf (get-kernel-fpu-sse-xxt70) (get-kernel-fpu-sse-xxt70))
           (setf (get-kernel-fpu-sse-xxt71) (get-kernel-fpu-sse-xxt71))
           (setf (get-kernel-fpu-sse-xxt72) (get-kernel-fpu-sse-xxt72))
           (setf (get-kernel-fpu-sse-xxt73) (get-kernel-fpu-sse-xxt73))
           (setf (get-kernel-fpu-sse-xxt74) (get-kernel-fpu-sse-xxt74))
           (setf (get-kernel-fpu-sse-xxt75) (get-kernel-fpu-sse-xxt75))
           (setf (get-kernel-fpu-sse-xxt76) (get-kernel-fpu-sse-xxt76))
           (setf (get-kernel-fpu-sse-xxt77) (get-kernel-fpu-sse-xxt77))
           (setf (get-kernel-fpu-sse-xxt78) (get-kernel-fpu-sse-xxt78))
           (setf (get-kernel-fpu-sse-xxt79) (get-kernel-fpu-sse-xxt79))
           (setf (get-kernel-fpu-sse-xxt7A) (get-kernel-fpu-sse-xxt7A))
           (setf (get-kernel-fpu-sse-xxt7B) (get-kernel-fpu-sse-xxt7B))
           (setf (get-kernel-fpu-sse-xxt7C) (get-kernel-fpu-sse-xxt7C))
           (setf (get-kernel-fpu-sse-xxt7D) (get-kernel-fpu-sse-xxt7D))
           (setf (get-kernel-fpu-sse-xxt7E) (get-kernel-fpu-sse-xxt7E))
           (setf (get-kernel-fpu-sse-xxt7F) (get-kernel-fpu-sse-xxt7F))
           (setf (get-kernel-fpu-sse-xxt80) (get-kernel-fpu-sse-xxt80))
           (setf (get-kernel-fpu-sse-xxt81) (get-kernel-fpu-sse-xxt81))
           (setf (get-kernel-fpu-sse-xxt82) (get-kernel-fpu-sse-xxt82))
           (setf (get-kernel-fpu-sse-xxt83) (get-kernel-fpu-sse-xxt83))
           (setf (get-kernel-fpu-sse-xxt84) (get-kernel-fpu-sse-xxt84))
           (setf (get-kernel-fpu-sse-xxt85) (get-kernel-fpu-sse-xxt85))
           (setf (get-kernel-fpu-sse-xxt86) (get-kernel-fpu-sse-xxt86))
           (setf (get-kernel-fpu-sse-xxt87) (get-kernel-fpu-sse-xxt87))
           (setf (get-kernel-fpu-sse-xxt88) (get-kernel-fpu-sse-xxt88))
           (setf (get-kernel-fpu-sse-xxt89) (get-kernel-fpu-sse-xxt89))
           (setf (get-kernel-fpu-sse-xxt8A) (get-kernel-fpu-sse-xxt8A))
           (setf (get-kernel-fpu-sse-xxt8B) (get-kernel-fpu-sse-xxt8B))
           (setf (get-kernel-fpu-sse-xxt8C) (get-kernel-fpu-sse-xxt8C))
           (setf (get-kernel-fpu-sse-xxt8D) (get-kernel-fpu-sse-xxt8D))
           (setf (get-kernel-fpu-sse-xxt8E) (get-kernel-fpu-sse-xxt8E))
           (setf (get-kernel-fpu-sse-xxt8F) (get-kernel-fpu-sse-xxt8F))
           (setf (get-kernel-fpu-sse-xxt90) (get-kernel-fpu-sse-xxt90))
           (setf (get-kernel-fpu-sse-xxt91) (get-kernel-fpu-sse-xxt91))
           (setf (get-kernel-fpu-sse-xxt92) (get-kernel-fpu-sse-xxt92))
           (setf (get-kernel-fpu-sse-xxt93) (get-kernel-fpu-sse-xxt93))
           (setf (get-kernel-fpu-sse-xxt94) (get-kernel-fpu-sse-xxt94))
           (setf (get-kernel-fpu-sse-xxt95) (get-kernel-fpu-sse-xxt95))
           (setf (get-kernel-fpu-sse-xxt96) (get-kernel-fpu-sse-xxt96))
           (setf (get-kernel-fpu-sse-xxt97) (get-kernel-fpu-sse-xxt97))
           (setf (get-kernel-fpu-sse-xxt98) (get-kernel-fpu-sse-xxt98))
           (setf (get-kernel-fpu-sse-xxt99) (get-kernel-fpu-sse-xxt99))
           (setf (get-kernel-fpu-sse-xxt9A) (get-kernel-fpu-sse-xxt9A))
           (setf (get-kernel-fpu-sse-xxt9B) (get-kernel-fpu-sse-xxt9B))
           (setf (get-kernel-fpu-sse-xxt9C) (get-kernel-fpu-sse-xxt9C))
           (setf (get-kernel-fpu-sse-xxt9D) (get-kernel-fpu-sse-xxt9D))
           (setf (get-kernel-fpu-sse-xxt9E) (get-kernel-fpu-sse-xxt9E))
           (setf (get-kernel-fpu-sse-xxt9F) (get-kernel-fpu-sse-xxt9F))
           (setf (get-kernel-fpu-sse-xxtA0) (get-kernel-fpu-sse-xxtA0))
           (setf (get-kernel-fpu-sse-xxtA1) (get-kernel-fpu-sse-xxtA1))
           (setf (get-kernel-fpu-sse-xxtA2) (get-kernel-fpu-sse-xxtA2))
           (setf (get-kernel-fpu-sse-xxtA3) (get-kernel-fpu-sse-xxtA3))
           (setf (get-kernel-fpu-sse-xxtA4) (get-kernel-fpu-sse-xxtA4))
           (setf (get-kernel-fpu-sse-xxtA5) (get-kernel-fpu-sse-xxtA5))
           (setf (get-kernel-fpu-sse-xxtA6) (get-kernel-fpu-sse-xxtA6))
           (setf (get-kernel-fpu-sse-xxtA7) (get-kernel-fpu-sse-xxtA7))
           (setf (get-kernel-fpu-sse-xxtA8) (get-kernel-fpu-sse-xxtA8))
           (setf (get-kernel-fpu-sse-xxtA9) (get-kernel-fpu-sse-xxtA9))
           (setf (get-kernel-fpu-sse-xxtAA) (get-kernel-fpu-sse-xxtAA))
           (setf (get-kernel-fpu-sse-xxtAB) (get-kernel-fpu-sse-xxtAB))
           (setf (get-kernel-fpu-sse-xxtAC) (get-kernel-fpu-sse-xxtAC))
           (setf (get-kernel-fpu-sse-xxtAD) (get-kernel-fpu-sse-xxtAD))
           (setf (get-kernel-fpu-sse-xxtAE) (get-kernel-fpu-sse-xxtAE))
           (setf (get-kernel-fpu-sse-xxtAF) (get-kernel-fpu-sse-xxtAF))
           (setf (get-kernel-fpu-sse-xxtB0) (get-kernel-fpu-sse-xxtB0))
           (setf (get-kernel-fpu-sse-xxtB1) (get-kernel-fpu-sse-xxtB1))
           (setf (get-kernel-fpu-sse-xxtB2) (get-kernel-fpu-sse-xxtB2))
           (setf (get-kernel-fpu-sse-xxtB3) (get-kernel-fpu-sse-xxtB3))
           (setf (get-kernel-fpu-sse-xxtB4) (get-kernel-fpu-sse-xxtB4))
           (setf (get-kernel-fpu-sse-xxtB5) (get-kernel-fpu-sse-xxtB5))
           (setf (get-kernel-fpu-sse-xxtB6) (get-kernel-fpu-sse-xxtB6))
           (setf (get-kernel-fpu-sse-xxtB7) (get-kernel-fpu-sse-xxtB7))
           (setf (get-kernel-fpu-sse-xxtB8) (get-kernel-fpu-sse-xxtB8))
           (setf (get-kernel-fpu-sse-xxtB9) (get-kernel-fpu-sse-xxtB9))
           (setf (get-kernel-fpu-sse-xxtBA) (get-kernel-fpu-sse-xxtBA))
           (setf (get-kernel-fpu-sse-xxtBB) (get-kernel-fpu-sse-xxtBB))
           (setf (get-kernel-fpu-sse-xxtBC) (get-kernel-fpu-sse-xxtBC))
           (setf (get-kernel-fpu-sse-xxtBD) (get-kernel-fpu-sse-xxtBD))
           (setf (get-kernel-fpu-sse-xxtBE) (get-kernel-fpu-sse-xxtBE))
           (setf (get-kernel-fpu-sse-xxtBF) (get-kernel-fpu-sse-xxtBF))
           (setf (get-kernel-fpu-sse-xxtC0) (get-kernel-fpu-sse-xxtC0))
           (setf (get-kernel-fpu-sse-xxtC1) (get-kernel-fpu-sse-xxtC1))
           (setf (get-kernel-fpu-sse-xxtC2) (get-kernel-fpu-sse-xxtC2))
           (setf (get-kernel-fpu-sse-xxtC3) (get-kernel-fpu-sse-xxtC3))
           (setf (get-kernel-fpu-sse-xxtC4) (get-kernel-fpu-sse-xxtC4))
           (setf (get-kernel-fpu-sse-xxtC5) (get-kernel-fpu-sse-xxtC5))
           (setf (get-kernel-fpu-sse-xxtC6) (get-kernel-fpu-sse-xxtC6))
           (setf (get-kernel-fpu-sse-xxtC7) (get-kernel-fpu-sse-xxtC7))
           (setf (get-kernel-fpu-sse-xxtC8) (get-kernel-fpu-sse-xxtC8))
           (setf (get-kernel-fpu-sse-xxtC9) (get-kernel-fpu-sse-xxtC9))
           (setf (get-kernel-fpu-sse-xxtCA) (get-kernel-fpu-sse-xxtCA))
           (setf (get-kernel-fpu-sse-xxtCB) (get-kernel-fpu-sse-xxtCB))
           (setf (get-kernel-fpu-sse-xxtCC) (get-kernel-fpu-sse-xxtCC))
           (setf (get-kernel-fpu-sse-xxtCD) (get-kernel-fpu-sse-xxtCD))
           (setf (get-kernel-fpu-sse-xxtCE) (get-kernel-fpu-sse-xxtCE))
           (setf (get-kernel-fpu-sse-xxtCF) (get-kernel-fpu-sse-xxtCF))
           (setf (get-kernel-fpu-sse-xxtD0) (get-kernel-fpu-sse-xxtD0))
           (setf (get-kernel-fpu-sse-xxtD1) (get-kernel-fpu-sse-xxtD1))
           (setf (get-kernel-fpu-sse-xxtD2) (get-kernel-fpu-sse-xxtD2))
           (setf (get-kernel-fpu-sse-xxtD3) (get-kernel-fpu-sse-xxtD3))
           (setf (get-kernel-fpu-sse-xxtD4) (get-kernel-fpu-sse-xxtD4))
           (setf (get-kernel-fpu-sse-xxtD5) (get-kernel-fpu-sse-xxtD5))
           (setf (get-kernel-fpu-sse-xxtD6) (get-kernel-fpu-sse-xxtD6))
           (setf (get-kernel-fpu-sse-xxtD7) (get-kernel-fpu-sse-xxtD7))
           (setf (get-kernel-fpu-sse-xxtD8) (get-kernel-fpu-sse-xxtD8))
           (setf (get-kernel-fpu-sse-xxtD9) (get-kernel-fpu-sse-xxtD9))
           (setf (get-kernel-fpu-sse-xxtDA) (get-kernel-fpu-sse-xxtDA))
           (setf (get-kernel-fpu-sse-xxtDB) (get-kernel-fpu-sse-xxtDB))
           (setf (get-kernel-fpu-sse-xxtDC) (get-kernel-fpu-sse-xxtDC))
           (setf (get-kernel-fpu-sse-xxtDD) (get-kernel-fpu-sse-xxtDD))
           (setf (get-kernel-fpu-sse-xxtDE) (get-kernel-fpu-sse-xxtDE))
           (setf (get-kernel-fpu-sse-xxtDF) (get-kernel-fpu-sse-xxtDF))
           (setf (get-kernel-fpu-sse-xxtE0) (get-kernel-fpu-sse-xxtE0))
           (setf (get-kernel-fpu-sse-xxtE1) (get-kernel-fpu-sse-xxtE1))
           (setf (get-kernel-fpu-sse-xxtE2) (get-kernel-fpu-sse-xxtE2))
           (setf (get-kernel-fpu-sse-xxtE3) (get-kernel-fpu-sse-xxtE3))
           (setf (get-kernel-fpu-sse-xxtE4) (get-kernel-fpu-sse-xxtE4))
           (setf (get-kernel-fpu-sse-xxtE5) (get-kernel-fpu-sse-xxtE5))
           (setf (get-kernel-fpu-sse-xxtE6) (get-kernel-fpu-sse-xxtE6))
           (setf (get-kernel-fpu-sse-xxtE7) (get-kernel-fpu-sse-xxtE7))
           (setf (get-kernel-fpu-sse-xxtE8) (get-kernel-fpu-sse-xxtE8))
           (setf (get-kernel-fpu-sse-xxtE9) (get-kernel-fpu-sse-xxtE9))
           (setf (get-kernel-fpu-sse-xxtEA) (get-kernel-fpu-sse-xxtEA))
           (setf (get-kernel-fpu-sse-xxtEB) (get-kernel-fpu-sse-xxtEB))
           (setf (get-kernel-fpu-sse-xxtEC) (get-kernel-fpu-sse-xxtEC))
           (setf (get-kernel-fpu-sse-xxtED) (get-kernel-fpu-sse-xxtED))
           (setf (get-kernel-fpu-sse-xxtEE) (get-kernel-fpu-sse-xxtEE))
           (setf (get-kernel-fpu-sse-xxtEF) (get-kernel-fpu-sse-xxtEF))
           (setf (get-kernel-fpu-sse-xxtF0) (get-kernel-fpu-sse-xxtF0))
           (setf (get-kernel-fpu-sse-xxtF1) (get-kernel-fpu-sse-xxtF1))
           (setf (get-kernel-fpu-sse-xxtF2) (get-kernel-fpu-sse-xxtF2))
           (setf (get-kernel-fpu-sse-xxtF3) (get-kernel-fpu-sse-xxtF3))
           (setf (get-kernel-fpu-sse-xxtF4) (get-kernel-fpu-sse-xxtF4))
           (setf (get-kernel-fpu-sse-xxtF5) (get-kernel-fpu-sse-xxtF5))
           (setf (get-kernel-fpu-sse-xxtF6) (get-kernel-fpu-sse-xxtF6))
           (setf (get-kernel-fpu-sse-xxtF7) (get-kernel-fpu-sse-xxtF7))
           (setf (get-kernel-fpu-sse-xxtF8) (get-kernel-fpu-sse-xxtF8))
           (setf (get-kernel-fpu-sse-xxtF9) (get-kernel-fpu-sse-xxtF9))
           (setf (get-kernel-fpu-sse-xxtFA) (get-kernel-fpu-sse-xxtFA))
           (setf (get-kernel-fpu-sse-xxtFB) (get-kernel-fpu-sse-xxtFB))
           (setf (get-kernel-fpu-sse-xxtFC) (get-kernel-fpu-sse-xxtFC))
           (setf (get-kernel-fpu-sse-xxtFD) (get-kernel-fpu-sse-xxtFD))
           (setf (get-kernel-fpu-sse-xxtFE) (get-kernel-fpu-sse-xxtFE))
           (setf (get-kernel-fpu-sse-xxtFF) (get-kernel-fpu-sse-xxtFF))
           (setf (get-kernel-fpu-sse-xxtMP) (get-kernel-fpu-sse-xxtMP))
           (setf (get-kernel-fpu-sse-xxtNO) (get-kernel-fpu-sse-xxtNO))
           (setf (get-kernel-fpu-sse-xxtNV) (get-kernel-fpu-sse-xxtNV))
           (setf (get-kernel-fpu-sse-xxtNZ) (get-kernel-fpu-sse-xxtNZ))
           (setf (get-kernel-fpu-sse-xxtOE) (get-kernel-fpu-sse-xxtOE))
           (setf (get-kernel-fpu-sse-xxtPB) (get-kernel-fpu-sse-xxtPB))
           (setf (get-kernel-fpu-sse-xxtPF) (get-kernel-fpu-sse-xxtPF))
           (setf (get-kernel-fpu-sse-xxtPG) (get-kernel-fpu-sse-xxtPG))
           (setf (get-kernel-fpu-sse-xxtPH) (get-kernel-fpu-sse-xxtPH))
           (setf (get-kernel-fpu-sse-xxtPL) (get-kernel-fpu-sse-xxtPL))
           (setf (get-kernel-fpu-sse-xxtPV) (get-kernel-fpu-sse-xxtPV))
           (setf (get-kernel-fpu-sse-xxtPZ) (get-kernel-fpu-sse-xxtPZ))
           (setf (get-kernel-fpu-sse-xxtSb) (get-kernel-fpu-sse-xxtSb))
           (setf (get-kernel-fpu-sse-xxtSc) (get-kernel-fpu-sse-xxtSc))
           (setf (get-kernel-fpu-sse-xxtSd) (get-kernel-fpu-sse-xxtSd))
           (setf (get-kernel-fpu-sse-xxtSe) (get-kernel-fpu-sse-xxtSe))
           (setf (get-kernel-fpu-sse-xxtSf) (get-kernel-fpu-sse-xxtSf))
           (setf (get-kernel-fpu-sse-xxtSh) (get-kernel-fpu-sse-xxtSh))
           (setf (get-kernel-fpu-sse-xxtSi) (get-kernel-fpu-sse-xxtSi))
           (setf (get-kernel-fpu-sse-xxtSs) (get-kernel-fpu-sse-xxtSs))
           (setf (get-kernel-fpu-sse-xxtSd) (get-kernel-fpu-sse-xxtSd))
           (setf (get-kernel-fpu-sse-xxtSe) (get-kernel-fpu-sse-xxtSe))
           (setf (get-kernel-fpu-sse-xxtSf) (get-kernel-fpu-sse-xxtSf))
           (setf (get-kernel-fpu-sse-xxtSh) (get-kernel-fpu-sse-xxtSh))
           (setf (get-kernel-fpu-sse-xxtSi) (get-kernel-fpu-sse-xxtSi))
           (setf (get-kernel-fpu-sse-xxtSs) (get-kernel-fpu-sse-xxtSs))
          

(if (processor-featurep processor 'mmx)
    (setf (get-kernel-fpu-sse-xxtMMX) (get-kernel-fpu-sse-xxtMMX))
 (error "This processor does not support MMX instructions."))

(setf (get-kernel-fpu-sse-xxtMN) (get-kernel-fpu-sse-xxtMN))
(setf (get-kernel-fpu-sse-xxtMO) (get-kernel-fpu-sse-xxtMO))
(setf (get-kernel-fpu-sse-xxtMP) (get-kernel-fpu-sse-xxtMP))
(setf (get-kernel-fpu-sse-xxtNO) (get-kernel-fpu-sse-xxtNO))
(setf (get-kernel-fpu-sse-xxtNV) (get-kernel-fpu-sse-xxtNV))
(setf (get-kernel-fpu-sse-xxtNZ) (get-kernel-fpu-sse-xxtNZ))
(setf (get-kernel-fpu-sse-xxtOE) (get-kernel-fpu-sse-xxtOE))
(setf (get-kernel-fpu-sse-xxtPB) (get-kernel-fpu-sse-xxtPB))
(setf (get-kernel-fpu-sse-xxtPF) (get-kernel-fpu-sse-xxtPF))
(setf (get-kernel-fpu-sse-xxtPG) (get-kernel-fpu-sse-xxtPG))
(setf (get-kernel-fpu-sse-xxtSA) (get-kernel-fpu-sse-xxtSA))
(setf (get-kernel-fpu-sse-xxtSD) (get-kernel-fpu-sse-xxtSD))
(setf (get-kernel-fpu-sse-xxtSE) (get-kernel-fpu-sse-xxtSE))
(setf (get-kernel-fpu-sse-xxtSF) (get-kernel-fpu-sse-xxtSF))
(setf (get-kernel-fpu-sse-xxtSH) (get-kernel-fpu-sse-xxtSH))
(setf (get-kernel-fpu-sse-xxtSI) (get-kernel-fpu-sse-xxtSI))
(setf (get-kernel-fpu-sse-xxtSZ) (get-kernel-fpu-sse-xxtSZ))
(setf (get-kernel-fpu-sse-xxtTa) (get-kernel-fpu-sse-xxtTa))
(setf (get-kernel-fpu-sse-xxtTb) (get-kernel-fpu-sse-xxtTb))
(setf (get-kernel-fpu-sse-xxtTc) (get-kernel-fpu-sse-xxtTc))
(setf (get-kernel-fpu-sse-xxtTd) (get-kernel-fpu-sse-xxtTd))
(setf (get-kernel-fpu-sse-xxtTn) (get-kernel-fpu-sse-xxtTn))
(setf (get-kernel-fpu-sse-xxtTs) (get-kernel-fpu-sse-xxtTs))
(setf (get-kernel-fpu-sse-xxtTv) (get-kernel-fpu-sse-xxtTv))
(setf (get-kernel-fpu-sse-xxtTz) (get-kernel-fpu-sse-xxtTz))
(setf (get-kernel-fpu-sse-xxtZa) (get-kernel-fpu-sse-xxtZa))
(setf (get-kernel-fpu-sse-xxtZb) (get-kernel-fpu-sse-xxtZb))
(setf (get-kernel-fpu-sse-xxtZc) (get-kernel-fpu-sse-xxtZc))
(setf (get-kernel-fpu-sse-xxtZd) (get-kernel-fpu-sse-xxtZd))
(setf (get-kernel-fpu-sse-xxtZn) (get-kernel-fpu-sse-xxtZn))
(setf (get-kernel-fpu-sse-xxtZs) (get-kernel-fpu-sse-xxtZs))
(setf (get-kernel-fpu-sse-xxtZv) (get-kernel-fpu-sse-xxtZv))
(setf (get-kernel-fpu-sse-xxtZz) (get-kernel-fpu-sse-xxtZz))
(setf (get-kernel-fpu-sse-xxtZp) (get-kernel-fpu-sse-xxtZp))
(setf (get-kernel-fpu-sse-xxtZl) (get-kernel-fpu-sse-xxtZl))
(setf (get-kernel-fpu-sse-xxtZm) (get-kernel-fpu-sse-xxtZm))
(setf (get-kernel-fpu-sse-xxtZr) (get-kernel-fpu-sse-xxtZr))
(setf (get-kernel-fpu-sse-xxtZw) (get-kernel-fpu-sse-xxtZw))
(setf (get-kernel-fpu-sse-xxtZx) (get-kernel-fpu-sse-xxtZx))
(setf (get-kernel-fpu-sse-xxtZz) (get-kernel-fpu-sse-xxtZz))
(setf (get-kernel-fpu-sse-xxtOu) (get-kernel-fpu-sse-xxtOu))
(setf (get-kernel-fpu-sse-xxtOv) (get-kernel-fpu-sse-xxtOv))
(setf (get-kernel-fpu-sse-xxtOw) (get-kernel-fpu-sse-xxtOw))
(setf (get-kernel-fpu-sse-xxtOy) (get-kernel-fpu-sse-xxtOy))
(setf (get-kernel-fpu-sse-xxtOz) (get-kernel-fpu-sse-xxtOz))
(setf (get-kernel-fpu-sse-xxtOz) (get-kernel-fpu-sse-xxtOz))
(in-package :k)
(include :k)

(defun get-kernel-fpu-sse-xxtOa ()
 (unwind-protect
       (setf (%rax) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq))))
    (get-kernel-fpu-unset-xxtOa))
 (%rax))

(defun get-kernel-fpu-sse-xxtOb ()
 (unwind-protect
       (setf (%rax) (flddq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOb))
 (%rax))

(defun get-kernel-fpu-sse-xxtOc ()
 (unwind-protect
       (setf (%rax) (fadddq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOc))
 (%rax))

(defun get-kernel-fpu-sse-xxtOd ()
 (unwind-protect
       (setf (%rax) (fsubdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOd))
 (%rax))

(defun get-kernel-fpu-sse-xxtOe ()
 (unwind-protect
       (setf (%rax) (fmuldq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOe))
 (%rax))

(defun get-kernel-fpu-sse-xxtOf ()
 (unwind-protect
       (setf (%rax) (fdivdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOf))
 (%rax))

(defun get-kernel-fpu-sse-xxtOg ()
 (unwind-protect
       (setf (%rax) (fanddq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOg))
 (%rax))

(defun get-kernel-fpu-sse-xxtOh ()
 (unwind-protect
       (setf (%rax) (forsdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOh))
 (%rax))

(defun get-kernel-fpu-sse-xxtOi ()
 (unwind-protect
       (setf (%rax) (fnotdq (lddq) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOi))
 (%rax))

(defun get-kernel-fpu-sse-xxtOj ()
 (unwind-protect
       (setf (%rax) (fcomdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOj))
 (%rax))

(defun get-kernel-fpu-sse-xxtOk ()
 (unwind-protect
       (setf (%rax) (fcvtdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOk))
 (%rax))

(defun get-kernel-fpu-sse-xxtOl ()
 (unwind-protect
       (setf (%rax) (fptrdq (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOl))
 (%rax))

(defun get-kernel-fpu-sse-xxtOm ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOm))
 (%rax))

(defun get-kernel-fpu-sse-xxtOn ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOn))
 (%rax))

(defun get-kernel-fpu-sse-xxtOo ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOo))
 (%rax))

(defun get-kernel-fpu-sse-xxtOq ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOq))
 (%rax))

(defun get-kernel-fpu-sse-xxtOr ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOr))
 (%rax))

(defun get-kernel-fpu-sse-xxtOs ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOs))
 (%rax))

(defun get-kernel-fpu-sse-xxtOt ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOt))
 (%rax))

(defun get-kernel-fpu-sse-xxtOu ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOu))
 (%rax))

(defun get-kernel-fpu-sse-xxtOv ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOv))
 (%rax))

(defun get-kernel-fpu-sse-xxtOw ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOw))
 (%rax))

(defun get-kernel-fpu-sse-xxtOx ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOx))
 (%rax))

(defun get-kernel-fpu-sse-xxtOy ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOy))
 (%rax))

(defun get-kernel-fpu-sse-xxtOz ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOz))
 (%rax))

(defun get-kernel-fpu-sse-xxtO0 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO0))
 (%rax))

(defun get-kernel-fpu-sse-xxtO1 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO1))
 (%rax))

(defun get-kernel-fpu-sse-xxtO2 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO2))
 (%rax))

(defun get-kernel-fpu-sse-xxtO3 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO3))
 (%rax))

(defun get-kernel-fpu-sse-xxtO4 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset_xxtO4))
 (%rax))

(defun get-kernel-fpu-sse-xxtO5 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO5))
 (%rax))

(defun get-kernel-fpu-sse-xxtO6 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO6))
 (%rax))

(defun get-kernel-fpu-sse-xxtO7 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO7))
 (%rax))

(defun get-kernel-fpu-sse-xxtO8 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO8))
 (%rax))

(defun get-kernel-fpu-sse-xxtO9 ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtO9))
 (%rax))

(defun get-kernel-fpu-sse-xxtOa ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOa))
 (%rax))

(defun get-kernel-fpu-sse-xxtOb ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOb))
 (%rax))

(defun get-kernel-fpu-sse-xxtOc ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOc))
 (%rax))

(defun get-kernel-fpu-sse-xxtOd ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOd))
 (%rax))

(defun get-kernel-fpu-sse-xxtOe ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOe))
 (%rax))

(defun get-kernel-fpu-sse-xxtOf ()
 (unwind-protect
       (setf (%rax) (fucomd (lddq) (mfld) (fst (ssdexc (lshd (ldmxcsr) 1) (lddq) (lddq)))))
    (get-kernel-fpu-unset-xxtOf))
 (%rax))

